[postgres]
host     = "aws-1-us-east-1.pooler.supabase.com"
port     = 5432
dbname   = "postgres"
user     = "postgres.zcmhvouncuyhjrgssocb"
password = "QxIQxYDQDFMcvky6"

MONGO_URI = "mongodb+srv://yw4537_db_user:10INlwn9TOC7AfsO@cluster0.w1bncvb.mongodb.net/?appName=Cluster0"
