[postgres]
host     = "aws-0-us-east-1.pooler.supabase.com"
port     = 5432
dbname   = "postgres"
user     = "postgres.YOUR_PROJECT_ID"
password = "YOUR_SUPABASE_PASSWORD"

MONGO_URI = "mongodb+srv://yw4537_db_user:YOUR_PASSWORD@cluster0.w1bncvb.mongodb.net/?appName=Cluster0"
